# -*- coding: utf-8 -*-
"""VIX_strategy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zzr8rye2Am5eXS4cF8sfpozrPDgorFoO
"""

# prompt: download the VIX index for the last 10 years and plot that on the chart

import yfinance as yf
import matplotlib.pyplot as plt

# Download VIX data for the last 10 years
vix = yf.download("^VIX", period="20y")

# Plot the VIX index
plt.figure(figsize=(12, 6))
plt.plot(vix['Close'])
plt.title('VIX Volatility Index (10 Years)')
plt.xlabel('Date')
plt.ylabel('VIX Value')
plt.grid(True)
plt.show()

# Calculate the daily change
vix['Daily Change'] = vix['Close'].diff()

# Plot the daily change
plt.figure(figsize=(12, 6))
plt.plot(vix['Daily Change'])
plt.title('Daily Change of VIX Volatility Index (10 Years)')
plt.xlabel('Date')
plt.ylabel('Daily Change')
plt.grid(True)
plt.show()